name: Events Demo1
on: 
  pull_request:
    types:
      - opened
    branches:
      - main #main
      - 'dev-*'
      - 'feat/**' # hi
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
      paths-ignore:
        - '.github/workflows/*'
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Output event data
          run: echo "${{ toJSON(github.event) }}"
        - name: Get code
