name: Upload Website
on:
  push:
    branches:
      - dev
      - prod
      - revert-*-dev
      - revert-*-prod
jobs:
  configure_env:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_API_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_API_SECRET_KEY}}
          aws-region: us-east-1
  deploy:
    needs: configure_env
    if: ((startsWith(github.ref_name, 'prod') || (startsWith(github.ref_name, 'revert-'))) && github.event_name == 'push')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_API_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_API_SECRET_KEY}}
          aws-region: us-east-1
      - name: Deploy to s3
        run: aws s3 sync . s3://webamarahostprod --exclude '*.git/*' --delete
