name: Upload Website
on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - prod  
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure AWS Crendentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static site to s3 Bucket for Dev
        run: aws s3 sync . s3://webamarahost --exclude '*.git/*'
  deploy_prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/prod' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure AWS Crendentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static site to s3 bucket for prod
        run: aws s3 sync . s3://webamrahostprod --exclude '*.git/*'
