name: Upload Website
on:
  pull_request:
     types: [closed]
     branches:
       - dev
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: configure AWS Crendentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_API_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_API_SECRET_KEY}}
          aws-region: us-east-1
      - name: Deploy static site to s3 Bucket for Dev
        run: aws s3 sync . s3://webamarahost --exclude '*.git/*'
      - name: Invalidate CDN
        run: aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths '/*
          
